# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c3f84b6c70efdde3c739db3e63d74cc7ad19642c2af665899a5f48ad2ded5022912607a95572426550f88e034097395f38072d890b01a6b727e316d082b583

test:
  secret_key_base: 0c2d5a61c40ae62ba5642594596125afcb5c2d9facd0e9cfe932a8c5601d71028b8882c75b2c1104cc3e960cdd1095e3b0ffb236105703c70f774d3a2ec9bbe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
